# -*- coding: utf-8 -*-
"""Oil_spill_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YNhFIXtIOZmL6ntAoh4u4zh67ep-SZwL
"""

!python --version

!pip install tensorflow==2.12.0 keras==2.12.0
!pip install efficientnet==1.1.0
!pip install segmentation-models==1.0.1

# Restart Colab runtime first (Runtime -> Restart runtime)
!pip install numpy==1.23.5 --quiet
!pip install tensorflow==2.12.0 keras==2.12.0 efficientnet==1.1.0 segmentation-models==1.0.1 --quiet

import os
os.environ["SM_FRAMEWORK"] = "tf.keras"

import tensorflow as tf
import segmentation_models as sm

sm.set_framework('tf.keras')

print("TF version:", tf.__version__)
print("Segmentation Models version:", sm.__version__)

# Change URLs below to exact Zenodo download links
!wget https://zenodo.org/record/15298010/files/images.zip?download=1 -O images.zip
!wget https://zenodo.org/record/15298010/files/masks.zip?download=1 -O masks.zip

!unzip images.zip -d /content/DeepSAR/images
!unzip masks.zip  -d /content/DeepSAR/masks

# Make sure parent folders exist
!mkdir -p /content/DeepSAR/images
!mkdir -p /content/DeepSAR/masks

# Unzip the downloaded datasets
!unzip -q images.zip -d /content/DeepSAR/images
!unzip -q masks.zip -d /content/DeepSAR/masks

!ls /content/DeepSAR/images
!ls /content/DeepSAR/masks

import os
from glob import glob

# Paths to images and masks
IMAGE_DIR = "/content/DeepSAR/images"
MASK_DIR  = "/content/DeepSAR/masks"

# Get all image and mask file paths, sorted
image_paths = sorted(glob(os.path.join(IMAGE_DIR, "*.png")))
mask_paths  = sorted(glob(os.path.join(MASK_DIR, "*.png")))

print(f"Total images: {len(image_paths)}")
print(f"Total masks: {len(mask_paths)}")

!ls /content/DeepSAR
!ls /content/DeepSAR/images
!ls /content/DeepSAR/masks

# Remove __MACOSX folders
!rm -rf /content/DeepSAR/__MACOSX
!rm -rf /content/DeepSAR/images/__MACOSX
!rm -rf /content/DeepSAR/masks/__MACOSX

# Move all images from subfolders to /images
!find /content/DeepSAR/images -type f -name "*.png" -exec mv {} /content/DeepSAR/images/ \;

# Move all masks from subfolders to /masks
!find /content/DeepSAR/masks -type f -name "*.png" -exec mv {} /content/DeepSAR/masks/ \;

# Check
!ls /content/DeepSAR/images | head
!ls /content/DeepSAR/masks | head

from glob import glob
IMAGE_DIR = "/content/DeepSAR/images"
MASK_DIR  = "/content/DeepSAR/masks"

image_paths = sorted(glob(IMAGE_DIR + "/*.png"))
mask_paths  = sorted(glob(MASK_DIR + "/*.png"))

print("Images:", len(image_paths), "Masks:", len(mask_paths))

from sklearn.model_selection import train_test_split

# First split: train + test
train_x, test_x, train_y, test_y = train_test_split(
    image_paths, mask_paths, test_size=0.2, random_state=42
)

# Second split: train + validation
train_x, val_x, train_y, val_y = train_test_split(
    train_x, train_y, test_size=0.2, random_state=42
)

print(f"Training: {len(train_x)} images")
print(f"Validation: {len(val_x)} images")
print(f"Testing: {len(test_x)} images")

from sklearn.model_selection import train_test_split

# First split: train + test
train_x, test_x, train_y, test_y = train_test_split(
    image_paths, mask_paths, test_size=0.15, random_state=42
)

# Second split: train + validation
train_x, val_x, train_y, val_y = train_test_split(
    train_x, train_y, test_size=0.15, random_state=42
)

print(f"Training: {len(train_x)} images")
print(f"Validation: {len(val_x)} images")
print(f"Testing: {len(test_x)} images")

def data_generator(images, masks, batch=8):
    while True:
        for i in range(0, len(images), batch):
            batch_x = images[i:i+batch]
            batch_y = masks[i:i+batch]

            imgs = []
            msks = []

            for img_path, mask_path in zip(batch_x, batch_y):
                img, msk = load_image_mask(img_path, mask_path)
                imgs.append(img)
                msks.append(msk)

            yield np.array(imgs), np.array(msks)

IMG_SIZE = 96
BATCH = 12
def load_image_mask(img_path, mask_path):

    # ----- IMAGE -----
    img = cv2.imread(img_path)
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = img.astype(np.float32)

    # DO NOT divide by 255 here
    img = preprocess_input(img)

    # ----- MASK -----
    mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
    mask = cv2.resize(mask, (IMG_SIZE, IMG_SIZE))

    # hard binary mask
    mask = (mask > 127).astype(np.float32)
    mask = np.expand_dims(mask, axis=-1)

    return img, mask


def data_generator(images, masks, batch=BATCH):
    while True:
        idx = np.random.permutation(len(images))
        for i in range(0, len(images), batch):
            batch_ids = idx[i:i+batch]
            imgs, msks = [], []

            for j in batch_ids:
                img, msk = load_image_mask(images[j], masks[j])
                imgs.append(img)
                msks.append(msk)

            yield np.array(imgs), np.array(msks)

def data_generator(images, masks, batch=BATCH):
    while True:
        idx = np.random.permutation(len(images))
        for i in range(0, len(images), batch):
            batch_ids = idx[i:i+batch]
            imgs, msks = [], []

            for j in batch_ids:
                img, msk = load_image_mask(images[j], masks[j])
                imgs.append(img)
                msks.append(msk)

            yield np.array(imgs), np.array(msks)

import os
import cv2
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from glob import glob
from sklearn.model_selection import train_test_split
import segmentation_models as sm

# Set framework
os.environ["SM_FRAMEWORK"] = "tf.keras"
sm.set_framework('tf.keras')
BACKBONE = 'mobilenetv2'
preprocess_input = sm.get_preprocessing(BACKBONE)

print("TF version:", tf.__version__)

IMG_SIZE = 96
BATCH = 12

def load_image_mask(img_path, mask_path):

    # ----- IMAGE -----
    img = cv2.imread(img_path)
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = img.astype(np.float32)

    # DO NOT divide by 255 here
    img = preprocess_input(img)

    # ----- MASK -----
    mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
    mask = cv2.resize(mask, (IMG_SIZE, IMG_SIZE))

    # hard binary mask
    mask = (mask > 127).astype(np.float32)
    mask = np.expand_dims(mask, axis=-1)

    return img, mask



def data_generator(images, masks, batch=BATCH):
    while True:
        idx = np.random.permutation(len(images))
        for i in range(0, len(images), batch):
            batch_ids = idx[i:i+batch]
            imgs, msks = [], []

            for j in batch_ids:
                img, msk = load_image_mask(images[j], masks[j])
                imgs.append(img)
                msks.append(msk)

            yield np.array(imgs), np.array(msks)

train_gen = data_generator(train_x, train_y, BATCH)
val_gen   = data_generator(val_x, val_y, BATCH)

steps_train = 120
steps_val   = 30

from tensorflow.keras import mixed_precision
#mixed_precision.set_global_policy('mixed_float16')

# Install the library if you haven't yet
!pip install segmentation-models --quiet

# Import the library
import segmentation_models as sm

# Set the framework for Keras (optional but recommended)
sm.set_framework('tf.keras')
sm.framework()

model = sm.Unet(
    BACKBONE,
    encoder_weights='imagenet',
    classes=1,
    activation='sigmoid'
)
model.compile(
    optimizer=tf.keras.optimizers.Adam(3e-4),
    loss="binary_crossentropy",
    metrics=[sm.metrics.iou_score]
)

model.summary()

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

checkpoint = ModelCheckpoint(
    "/content/unet_oilspill_best.h5",
    monitor="val_iou_score",
    save_best_only=True,
    mode="max",
    verbose=1
)

earlystop = EarlyStopping(
    monitor="val_iou_score",
    patience=3,
    mode="max",
    restore_best_weights=True
)

x, y = next(train_gen)
print("Image batch:", x.shape)
print("Mask batch:", y.shape)
print("Mask unique:", np.unique(y))

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

checkpoint = ModelCheckpoint(
    "/content/drive/MyDrive/unet_best.h5",
    monitor="val_iou_score",
    save_best_only=True,
    mode="max",
    verbose=1
)

earlystop = EarlyStopping(
    monitor="val_iou_score",
    patience=3,
    mode="max",
    restore_best_weights=True
)

history = model.fit(
    train_gen,
    validation_data=val_gen,
    steps_per_epoch=80,
    validation_steps=20,
    epochs=20,
    callbacks=[checkpoint, earlystop]
)


model.save("/content/drive/MyDrive/unet_final.h5")
model.save("/content/drive/MyDrive/unet_savedmodel")

from google.colab import files
import shutil

# Download the .h5 model
files.download("/content/drive/MyDrive/unet_final.h5")

# For the SavedModel folder, first zip it
shutil.make_archive("/content/unet_savedmodel", 'zip', "/content/drive/MyDrive/unet_savedmodel")

# Then download the zip
files.download("/content/unet_savedmodel.zip")

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

checkpoint = ModelCheckpoint(
    "/content/drive/MyDrive/unet_best.h5",
    monitor="val_iou_score",
    save_best_only=True,
    mode="max",
    verbose=1
)

earlystop = EarlyStopping(
    monitor="val_iou_score",
    patience=3,
    mode="max",
    restore_best_weights=True
)

history = model.fit(
    train_gen,
    validation_data=val_gen,
    steps_per_epoch=80,
    validation_steps=20,
    epochs=20,
    callbacks=[checkpoint, earlystop]
)


model.save("/content/drive/MyDrive/unet_final.h5")
model.save("/content/drive/MyDrive/unet_savedmodel")

from google.colab import files
import shutil

# Download the .h5 model
files.download("/content/drive/MyDrive/unet_final.h5")

# For the SavedModel folder, first zip it
shutil.make_archive("/content/unet_savedmodel", 'zip', "/content/drive/MyDrive/unet_savedmodel")

# Then download the zip
files.download("/content/unet_savedmodel.zip")

# --- 8. Callbacks ---
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau

checkpoint = ModelCheckpoint(
    "/content/drive/MyDrive/unet_best.h5",
    monitor="val_iou_score",
    save_best_only=True,
    mode="max",
    verbose=1
)

earlystop = EarlyStopping(
    monitor="val_iou_score",
    patience=6,  # allow temporary drops in IoU
    mode="max",
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor="val_iou_score",
    factor=0.5,
    patience=3,
    min_lr=1e-6,
    mode="max",
    verbose=1
)

# --- 9. Train model ---
history = model.fit(
    train_gen,
    validation_data=val_gen,
    steps_per_epoch=80,
    validation_steps=20,
    epochs=20,
    callbacks=[checkpoint, earlystop, reduce_lr]
)

# --- 10. Save models ---
model.save("/content/drive/MyDrive/unet_final.h5")
model.save("/content/drive/MyDrive/unet_savedmodel")

# --- 11. Download models (optional) ---
from google.colab import files
import shutil

# Download .h5
files.download("/content/drive/MyDrive/unet_final.h5")

# Download SavedModel folder as zip
shutil.make_archive("/content/unet_savedmodel", 'zip', "/content/drive/MyDrive/unet_savedmodel")
files.download("/content/unet_savedmodel.zip")

model.save("/content/drive/MyDrive/unet_final.keras")

# --- 1. Save model in Keras format ---
keras_path = "/content/unet_final.keras"
model.save(keras_path)
print(f"Model saved at {keras_path}")

# --- 2. Download the .keras model ---
from google.colab import files

files.download(keras_path)

import tensorflow as tf
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau

# ----------------------------
# Custom Dice + BCE Loss
# ----------------------------
def dice_coef(y_true, y_pred, smooth=1):
    y_true_f = tf.reshape(y_true, [-1])
    y_pred_f = tf.reshape(y_pred, [-1])
    intersection = tf.reduce_sum(y_true_f * y_pred_f)
    return (2. * intersection + smooth) / (tf.reduce_sum(y_true_f) + tf.reduce_sum(y_pred_f) + smooth)

def dice_loss(y_true, y_pred):
    return 1 - dice_coef(y_true, y_pred)

def bce_dice_loss(y_true, y_pred):
    bce = tf.keras.losses.BinaryCrossentropy()(y_true, y_pred)
    return bce + dice_loss(y_true, y_pred)

# ----------------------------
# Callbacks
# ----------------------------
checkpoint = ModelCheckpoint(
    "unet_best.h5",               # save best model locally
    monitor="val_loss",           # track validation loss (can also track val_dice_coef)
    save_best_only=True,
    mode="min",
    verbose=1
)

earlystop = EarlyStopping(
    monitor="val_loss",
    patience=8,                   # stop if no improvement for 8 epochs
    mode="min",
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=3,
    min_lr=1e-6,
    verbose=1
)

# ----------------------------
# Train model
# ----------------------------
EPOCHS = 50  # safe longer training

history = model.fit(
    train_gen,
    validation_data=val_gen,
    steps_per_epoch=80,
    validation_steps=20,
    epochs=EPOCHS,
    callbacks=[checkpoint, earlystop, reduce_lr]
)

# ----------------------------
# Save model for Keras & SavedModel
# ----------------------------
model.save("unet_final.h5")                 # Keras H5
model.save("unet_savedmodel")              # TensorFlow SavedModel folder

# Optional: Download in Colab
try:
    from google.colab import files
    files.download("unet_final.h5")
except:
    print("Local environment: download manually from filesystem.")

